apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdspost
spec:
  forProvider:
    region: us-east-1
    dbInstanceClass: db.t2.micro
    masterUsername: masteruser
    allocatedStorage: 5
    engine: postgres
    engineVersion: "12"
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: rdspost
