apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: pro1-vpc
spec:
  forProvider:
    region: us-east-1
    cidrBlock: 192.168.0.0/16
    tags:
    - key: Name
      value: suman-vpc
    instanceTenancy: default
  providerConfigRef:
    name: default
